version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vehicle_transfers_db
    restart: always
    environment:
      POSTGRES_DB: vehicle_transfers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_transfers_api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: vehicle_transfers
      NODE_ENV: development
      DB_SSL_REQUIRED: false
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
